// apps/web/src/pages/Analytics.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { RouterLink } from 'vue-router'

type Period = 'week' | 'month' | 'quarter' | 'year'

type CategoryPerformance = {
  category: string
  tests: number
  averageScore: number
  bestScore: number
  improvement: number
}

const selectedPeriod = ref<Period>('month')

const analytics = {
  overallStats: {
    totalTests: 25,
    averageScore: 78,
    totalTimeSpent: 15_600,
    improvementRate: 12,
    streak: 7,
  },
  categoryPerformance: [
    { category: 'General Knowledge', tests: 8, averageScore: 82, bestScore: 95, improvement: 15 },
    { category: 'Aptitude', tests: 6, averageScore: 75, bestScore: 88, improvement: 8 },
    { category: 'Reasoning', tests: 5, averageScore: 85, bestScore: 92, improvement: 18 },
    { category: 'English', tests: 3, averageScore: 68, bestScore: 78, improvement: -5 },
    { category: 'Mathematics', tests: 3, averageScore: 72, bestScore: 85, improvement: 22 },
  ],
  weeklyProgress: [
    { week: 'Week 1', tests: 3, averageScore: 65 },
    { week: 'Week 2', tests: 5, averageScore: 72 },
    { week: 'Week 3', tests: 4, averageScore: 78 },
    { week: 'Week 4', tests: 6, averageScore: 82 },
    { week: 'Week 5', tests: 7, averageScore: 85 },
  ],
  timeAnalysis: {
    averageTimePerQuestion: 45,
    fastestTest: 1200,
    slowestTest: 2400,
    optimalTimeRange: [30, 60],
  },
  strengths: ['Pattern Recognition', 'Logical Reasoning', 'World Geography'],
  weaknesses: ['Grammar Rules', 'Mathematical Calculations', 'Current Events'],
}

const formatDuration = (seconds: number) => {
  const hours = Math.floor(seconds / 3600)
  const minutes = Math.floor((seconds % 3600) / 60)
  if (hours > 0) {
    return `${hours}h ${minutes}m`
  }
  return `${minutes}m`
}

const scoreColour = (score: number) => {
  if (score >= 80) return 'text-emerald-600'
  if (score >= 60) return 'text-amber-600'
  return 'text-rose-600'
}

const improvementColour = (value: number) => {
  if (value > 0) return 'text-emerald-600'
  if (value < 0) return 'text-rose-600'
  return 'text-slate-500'
}

const improvementPrefix = (value: number) => (value > 0 ? '+' : value < 0 ? '−' : '')

const timePerQuestion = computed(() => `${analytics.timeAnalysis.averageTimePerQuestion}s`)
const optimalTimeRange = computed(
  () => `${analytics.timeAnalysis.optimalTimeRange[0]}s – ${analytics.timeAnalysis.optimalTimeRange[1]}s`
)

const periodLabel = computed(() => {
  switch (selectedPeriod.value) {
    case 'week':
      return 'this week'
    case 'quarter':
      return 'this quarter'
    case 'year':
      return 'this year'
    default:
      return 'this month'
  }
})

const progressBarWidth = (value: number) => `${Math.min(Math.max(value, 0), 100)}%`

const weeklyAverage = computed(() =>
  Math.round(
    analytics.weeklyProgress.reduce((sum, entry) => sum + entry.averageScore, 0) /
      analytics.weeklyProgress.length
  )
)
</script>

<template>
  <section class="space-y-10">
    <header class="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between">
      <div class="flex items-start gap-4">
        <RouterLink
          :to="{ name: 'dashboard' }"
          class="inline-flex items-center gap-2 rounded-full border border-slate-200 px-4 py-2 text-xs font-semibold uppercase tracking-widest text-slate-600 transition hover:border-slate-300 hover:text-slate-900"
        >
          <span aria-hidden="true">←</span>
          Back to dashboard
        </RouterLink>
        <div>
          <p class="text-xs font-semibold uppercase tracking-[0.3em] text-slate-400">Insights</p>
          <h1 class="mt-2 text-3xl font-semibold text-slate-900">Performance analytics</h1>
          <p class="mt-2 max-w-xl text-sm text-slate-500">
            Track how your preparation evolves across weeks, subjects, and practice types.
          </p>
        </div>
      </div>
      <label class="flex items-center gap-3 text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">
        Period
        <select
          v-model="selectedPeriod"
          class="rounded-2xl border border-slate-200 px-4 py-2 text-sm font-medium text-slate-700 focus:border-slate-400 focus:outline-none"
        >
          <option value="week">This week</option>
          <option value="month">This month</option>
          <option value="quarter">This quarter</option>
          <option value="year">This year</option>
        </select>
      </label>
    </header>

    <div class="grid gap-6 lg:grid-cols-5">
      <article class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
        <p class="text-xs font-semibold uppercase tracking-[0.25em] text-slate-400">Total tests</p>
        <p class="mt-3 text-3xl font-semibold text-slate-900">{{ analytics.overallStats.totalTests }}</p>
        <p class="text-xs text-slate-500">Completed in {{ periodLabel }}</p>
      </article>
      <article class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
        <p class="text-xs font-semibold uppercase tracking-[0.25em] text-slate-400">Average score</p>
        <p :class="['mt-3 text-3xl font-semibold', scoreColour(analytics.overallStats.averageScore)]">
          {{ analytics.overallStats.averageScore }}%
        </p>
        <div class="mt-3 h-2 rounded-full bg-slate-100">
          <div
            class="h-full rounded-full bg-gradient-to-r from-indigo-500 via-sky-500 to-emerald-500"
            :style="{ width: progressBarWidth(analytics.overallStats.averageScore) }"
          />
        </div>
      </article>
      <article class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
        <p class="text-xs font-semibold uppercase tracking-[0.25em] text-slate-400">Study time</p>
        <p class="mt-3 text-3xl font-semibold text-slate-900">{{ formatDuration(analytics.overallStats.totalTimeSpent) }}</p>
        <p class="text-xs text-slate-500">Across quizzes and practice</p>
      </article>
      <article class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
        <p class="text-xs font-semibold uppercase tracking-[0.25em] text-slate-400">Improvement</p>
        <p :class="['mt-3 text-3xl font-semibold', improvementColour(analytics.overallStats.improvementRate)]">
          +{{ analytics.overallStats.improvementRate }}%
        </p>
        <p class="text-xs text-slate-500">Compared to last {{ periodLabel }}</p>
      </article>
      <article class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
        <p class="text-xs font-semibold uppercase tracking-[0.25em] text-slate-400">Study streak</p>
        <p class="mt-3 text-3xl font-semibold text-indigo-600">{{ analytics.overallStats.streak }}</p>
        <p class="text-xs text-slate-500">Days in a row</p>
      </article>
    </div>

    <div class="grid gap-6 xl:grid-cols-[1.5fr,1fr]">
      <section class="space-y-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
        <header class="flex items-center justify-between">
          <div>
            <h2 class="text-lg font-semibold text-slate-900">Category performance</h2>
            <p class="text-xs text-slate-500">Your strongest and weakest subjects</p>
          </div>
        </header>
        <ul class="space-y-5 text-sm">
          <li
            v-for="category in analytics.categoryPerformance"
            :key="category.category"
            class="space-y-3"
          >
            <div class="flex items-center justify-between">
              <div class="flex items-center gap-3">
                <span class="font-semibold text-slate-800">{{ category.category }}</span>
                <span class="rounded-full border border-slate-200 px-3 py-1 text-xs text-slate-500">
                  {{ category.tests }} tests
                </span>
              </div>
              <div class="flex items-center gap-3">
                <span :class="['font-semibold', scoreColour(category.averageScore)]">
                  {{ category.averageScore }}%
                </span>
                <span :class="['text-xs font-semibold', improvementColour(category.improvement)]">
                  {{ improvementPrefix(category.improvement) }}{{ Math.abs(category.improvement) }}%
                </span>
              </div>
            </div>
            <div class="h-2 rounded-full bg-slate-100">
              <div
                class="h-full rounded-full bg-gradient-to-r from-indigo-500 via-sky-500 to-emerald-500"
                :style="{ width: progressBarWidth(category.averageScore) }"
              />
            </div>
            <div class="flex justify-between text-xs text-slate-500">
              <span>Avg {{ category.averageScore }}%</span>
              <span>Best {{ category.bestScore }}%</span>
            </div>
          </li>
        </ul>
      </section>

      <aside class="space-y-6">
        <section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
          <h2 class="text-lg font-semibold text-slate-900">Time analysis</h2>
          <dl class="mt-4 space-y-3 text-sm text-slate-600">
            <div class="flex items-center justify-between">
              <dt class="text-slate-500">Average per question</dt>
              <dd class="font-semibold text-slate-900">{{ timePerQuestion }}</dd>
            </div>
            <div class="flex items-center justify-between">
              <dt class="text-slate-500">Fastest test</dt>
              <dd class="font-semibold text-slate-900">{{ formatDuration(analytics.timeAnalysis.fastestTest) }}</dd>
            </div>
            <div class="flex items-center justify-between">
              <dt class="text-slate-500">Slowest test</dt>
              <dd class="font-semibold text-slate-900">{{ formatDuration(analytics.timeAnalysis.slowestTest) }}</dd>
            </div>
            <div class="flex items-center justify-between">
              <dt class="text-slate-500">Optimal range</dt>
              <dd class="font-semibold text-slate-900">{{ optimalTimeRange }}</dd>
            </div>
          </dl>
        </section>

        <section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
          <h2 class="text-lg font-semibold text-slate-900">Focus areas</h2>
          <div class="mt-4 grid gap-4 text-sm text-slate-600">
            <div>
              <p class="text-xs font-semibold uppercase tracking-[0.2em] text-emerald-600">Strengths</p>
              <ul class="mt-2 space-y-2">
                <li
                  v-for="item in analytics.strengths"
                  :key="item"
                  class="rounded-2xl border border-emerald-100 bg-emerald-50 px-4 py-2 text-emerald-700"
                >
                  {{ item }}
                </li>
              </ul>
            </div>
            <div>
              <p class="text-xs font-semibold uppercase tracking-[0.2em] text-rose-600">Weaknesses</p>
              <ul class="mt-2 space-y-2">
                <li
                  v-for="item in analytics.weaknesses"
                  :key="item"
                  class="rounded-2xl border border-rose-100 bg-rose-50 px-4 py-2 text-rose-700"
                >
                  {{ item }}
                </li>
              </ul>
            </div>
          </div>
        </section>
      </aside>
    </div>

    <section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
      <header class="flex flex-col gap-2 md:flex-row md:items-center md:justify-between">
        <div>
          <h2 class="text-lg font-semibold text-slate-900">Weekly progress</h2>
          <p class="text-xs text-slate-500">Average score trend across recent weeks</p>
        </div>
        <p class="text-xs font-semibold uppercase tracking-[0.2em] text-indigo-600">
          Weekly average {{ weeklyAverage }}%
        </p>
      </header>
      <div class="mt-6 grid gap-4 md:grid-cols-5">
        <div
          v-for="entry in analytics.weeklyProgress"
          :key="entry.week"
          class="rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm"
        >
          <p class="text-xs font-semibold uppercase tracking-[0.25em] text-slate-500">{{ entry.week }}</p>
          <p class="mt-3 text-2xl font-semibold text-slate-900">{{ entry.averageScore }}%</p>
          <p class="text-xs text-slate-500">{{ entry.tests }} tests</p>
        </div>
      </div>
    </section>
  </section>
</template>

// legacy_frontend/app/analytics/page.tsx
"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"
import { Badge } from "@/components/ui/badge"
import { BarChart3, TrendingUp, TrendingDown, Target, Clock, BookOpen, Trophy, ArrowLeft } from "lucide-react"
import Link from "next/link"

// Mock analytics data
const mockAnalytics = {
  overallStats: {
    totalTests: 25,
    averageScore: 78,
    totalTimeSpent: 15600, // seconds
    improvementRate: 12, // percentage
    streak: 7, // days
  },
  categoryPerformance: [
    { category: "General Knowledge", tests: 8, averageScore: 82, bestScore: 95, improvement: 15 },
    { category: "Aptitude", tests: 6, averageScore: 75, bestScore: 88, improvement: 8 },
    { category: "Reasoning", tests: 5, averageScore: 85, bestScore: 92, improvement: 18 },
    { category: "English", tests: 3, averageScore: 68, bestScore: 78, improvement: -5 },
    { category: "Mathematics", tests: 3, averageScore: 72, bestScore: 85, improvement: 22 },
  ],
  weeklyProgress: [
    { week: "Week 1", tests: 3, averageScore: 65 },
    { week: "Week 2", tests: 5, averageScore: 72 },
    { week: "Week 3", tests: 4, averageScore: 78 },
    { week: "Week 4", tests: 6, averageScore: 82 },
    { week: "Week 5", tests: 7, averageScore: 85 },
  ],
  timeAnalysis: {
    averageTimePerQuestion: 45, // seconds
    fastestTest: 1200, // seconds
    slowestTest: 2400, // seconds
    optimalTimeRange: [30, 60], // seconds per question
  },
  strengths: ["Pattern Recognition", "Logical Reasoning", "World Geography"],
  weaknesses: ["Grammar Rules", "Mathematical Calculations", "Current Events"],
}

export default function AnalyticsPage() {
  const [selectedPeriod, setSelectedPeriod] = useState("month")

  const formatTime = (seconds: number) => {
    const hours = Math.floor(seconds / 3600)
    const minutes = Math.floor((seconds % 3600) / 60)
    return hours > 0 ? `${hours}h ${minutes}m` : `${minutes}m`
  }

  const getScoreColor = (score: number) => {
    if (score >= 80) return "text-green-600"
    if (score >= 60) return "text-yellow-600"
    return "text-red-600"
  }

  const getImprovementColor = (improvement: number) => {
    if (improvement > 0) return "text-green-600"
    if (improvement < 0) return "text-red-600"
    return "text-muted-foreground"
  }

  const getImprovementIcon = (improvement: number) => {
    if (improvement > 0) return <TrendingUp className="h-4 w-4" />
    if (improvement < 0) return <TrendingDown className="h-4 w-4" />
    return null
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border bg-card">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Button variant="ghost" size="sm" asChild>
                <Link href="/dashboard">
                  <ArrowLeft className="h-4 w-4 mr-2" />
                  Back to Dashboard
                </Link>
              </Button>
              <div className="flex items-center gap-2">
                <BarChart3 className="h-8 w-8 text-secondary" />
                <h1 className="text-2xl font-bold text-foreground">Performance Analytics</h1>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <select
                value={selectedPeriod}
                onChange={(e) => setSelectedPeriod(e.target.value)}
                className="px-3 py-2 border border-border rounded-md bg-background text-foreground"
              >
                <option value="week">This Week</option>
                <option value="month">This Month</option>
                <option value="quarter">This Quarter</option>
                <option value="year">This Year</option>
              </select>
            </div>
          </div>
        </div>
      </header>

      <div className="container mx-auto px-4 py-8">
        {/* Overall Stats */}
        <div className="grid grid-cols-1 md:grid-cols-5 gap-6 mb-8">
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Total Tests</CardTitle>
              <BookOpen className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{mockAnalytics.overallStats.totalTests}</div>
              <p className="text-xs text-muted-foreground">completed</p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Average Score</CardTitle>
              <Target className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className={`text-2xl font-bold ${getScoreColor(mockAnalytics.overallStats.averageScore)}`}>
                {mockAnalytics.overallStats.averageScore}%
              </div>
              <Progress value={mockAnalytics.overallStats.averageScore} className="mt-2" />
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Study Time</CardTitle>
              <Clock className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{formatTime(mockAnalytics.overallStats.totalTimeSpent)}</div>
              <p className="text-xs text-muted-foreground">total time</p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Improvement</CardTitle>
              <TrendingUp className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-green-600">+{mockAnalytics.overallStats.improvementRate}%</div>
              <p className="text-xs text-muted-foreground">vs last month</p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Study Streak</CardTitle>
              <Trophy className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-secondary">{mockAnalytics.overallStats.streak}</div>
              <p className="text-xs text-muted-foreground">days</p>
            </CardContent>
          </Card>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-8">
          {/* Category Performance */}
          <Card>
            <CardHeader>
              <CardTitle>Category Performance</CardTitle>
              <CardDescription>Your performance across different subjects</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {mockAnalytics.categoryPerformance.map((category) => (
                  <div key={category.category} className="space-y-2">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <span className="font-medium text-sm">{category.category}</span>
                        <Badge variant="outline" className="text-xs">
                          {category.tests} tests
                        </Badge>
                      </div>
                      <div className="flex items-center gap-2">
                        <span className={`text-sm font-bold ${getScoreColor(category.averageScore)}`}>
                          {category.averageScore}%
                        </span>
                        <div className={`flex items-center gap-1 ${getImprovementColor(category.improvement)}`}>
                          {getImprovementIcon(category.improvement)}
                          <span className="text-xs">{Math.abs(category.improvement)}%</span>
                        </div>
                      </div>
                    </div>
                    <Progress value={category.averageScore} className="h-2" />
                    <div className="flex justify-between text-xs text-muted-foreground">
                      <span>Avg: {category.averageScore}%</span>
                      <span>Best: {category.bestScore}%</span>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* Weekly Progress */}
          <Card>
            <CardHeader>
              <CardTitle>Weekly Progress</CardTitle>
              <CardDescription>Your improvement over the past 5 weeks</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {mockAnalytics.weeklyProgress.map((week, index) => (
                  <div key={week.week} className="flex items-center gap-4">
                    <div className="w-16 text-sm text-muted-foreground">{week.week}</div>
                    <div className="flex-1">
                      <div className="flex items-center justify-between mb-1">
                        <span className="text-sm">{week.tests} tests</span>
                        <span className={`text-sm font-bold ${getScoreColor(week.averageScore)}`}>
                          {week.averageScore}%
                        </span>
                      </div>
                      <Progress value={week.averageScore} className="h-2" />
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Time Analysis */}
          <Card>
            <CardHeader>
              <CardTitle>Time Analysis</CardTitle>
              <CardDescription>Your test-taking speed insights</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <span className="text-sm text-muted-foreground">Avg per question</span>
                  <span className="font-medium">{mockAnalytics.timeAnalysis.averageTimePerQuestion}s</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm text-muted-foreground">Fastest test</span>
                  <span className="font-medium">{formatTime(mockAnalytics.timeAnalysis.fastestTest)}</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm text-muted-foreground">Slowest test</span>
                  <span className="font-medium">{formatTime(mockAnalytics.timeAnalysis.slowestTest)}</span>
                </div>
                <div className="pt-2 border-t border-border">
                  <p className="text-xs text-muted-foreground mb-2">Optimal time per question:</p>
                  <p className="text-sm font-medium text-secondary">
                    {mockAnalytics.timeAnalysis.optimalTimeRange[0]}s - {mockAnalytics.timeAnalysis.optimalTimeRange[1]}
                    s
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Strengths */}
          <Card>
            <CardHeader>
              <CardTitle>Your Strengths</CardTitle>
              <CardDescription>Topics you excel at</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-2">
                {mockAnalytics.strengths.map((strength, index) => (
                  <div key={index} className="flex items-center gap-2">
                    <div className="w-2 h-2 rounded-full bg-green-500"></div>
                    <span className="text-sm">{strength}</span>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* Areas for Improvement */}
          <Card>
            <CardHeader>
              <CardTitle>Areas for Improvement</CardTitle>
              <CardDescription>Topics to focus on</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-2">
                {mockAnalytics.weaknesses.map((weakness, index) => (
                  <div key={index} className="flex items-center gap-2">
                    <div className="w-2 h-2 rounded-full bg-yellow-500"></div>
                    <span className="text-sm">{weakness}</span>
                  </div>
                ))}
              </div>
              <div className="pt-4 border-t border-border mt-4">
                <Button size="sm" className="w-full" asChild>
                  <Link href="/categories">Practice These Topics</Link>
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
